name: deploy dev

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # this prevents concurrent builds
    concurrency: dev-environment

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::157522218258:role/GitHubActionsRole
          role-session-name: GithubActionsSession

      - name: npm ci
        run: npm ci

      # this provisions a temporary stage called 'ci-dev'
      - name: deploy temp environment
        run: npx sls deploy -s ci-dev

      # this generates the .env file for the 'ci-dev' stage
      - name: export env
        run: npx sls export-env --all -s ci-dev

      # this runs the integration test against the 'ci-dev' stage
      - name: run integration test
        run: npx cross-env TEST_MODE=handler jest

      # this runs the acceptance test against the 'ci-dev' stage
      - name: run acceptance tests
        run: npx cross-env TEST_MODE=http jest

      # delete the 'ci-dev' stage
      - name: destroy temp environment
        run: npx sls remove -s ci-dev

      # deploy to the ACTUAL dev stage
      - name: deploy to dev
        run: npx sls deploy